name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: []
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: test
    attributes:
      label: Test
      description: Example Description
