name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: test
    attributes:
      label: Test
      description: Example Description
  - type: dropdown
    id: dropdown-example
    attributes:
      label: Dropdown
      description: Lorum ipsum
      options:
        - First option
        - Second option
    validations:
      required: false
