name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: test
    attributes:
      label: Test
      description: Example Description
  - type: input
    id: log
    attributes:
      label: Log
      description: |-
        **Windows:** Hit Windows Key + R and type in `%appdata%`. Open the `.minecraft` folder.
        **macOS:** On the bar at the top of your screen in Finder, click `Go`, then click `Go to Folder` and type `~/Library/Application Support/Minecraft`, then hit enter.
        **Linux:** `.minecraft` is located in your home folder. `~/.minecraft`

        Open your Minecraft folder and send the file `latest.log` from `.minecraft/logs`.
  - type: dropdown
    id: dropdown-example
    attributes:
      label: Dropdown
      description: Lorum ipsum
      options:
        - First option
        - Second option
    validations:
      required: false
